stage: production
workshop_motd_scripts:
  - file: 10-message
    template: script/{{ stage }}.j2
    message: "Welcome to the production environment"

php:
  enabled: true
  config:
    error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
    display_errors: False
    memory_limit: 256M
