---
- hosts: webservers

  become: true

  roles:
    - nginx
    - php
    - wordpress

  tasks:
    # CONFIG
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
