---
- name: Cleanup
  ansible.builtin.file:
    path: "/var/www/{{ http_root }}/wordpress"
    state: absent
  tags:
    - cleanup

- name: Download and unpack latest WordPress
  ansible.builtin.unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ http_root }}"
    remote_src: yes
    creates: "/var/www/{{ http_root }}/wordpress"
  tags:
    - installation

- name: Set ownership
  ansible.builtin.file:
    path: "/var/www/{{ http_root }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  tags:
    - config

- name: Set up wp-config
  ansible.builtin.template:
    src: "wp-config.php.j2"
    dest: "/var/www/{{ http_root }}/wordpress/wp-config.php"
  tags:
    - config
