---
- name: Install MySQL and dependencies
  ansible.builtin.package:
    name: python3-mysqldb
    state: present
    update_cache: yes
  tags:
    - installation

- name: Install MariaDB server
  ansible.builtin.apt:
    name: mariadb-server
    state: present
  tags:
    - installation

- name: Update root user password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    check_implicit_admin: true
    column_case_sensitive: true
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
    - configuration

- name: Update .my.cnf
  ansible.builtin.template:
    src: "my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600
  tags:
    - configuration

- name: Remove anonymous users
  mysql_user:
    user: ""
    state: absent
    column_case_sensitive: true
  tags:
    - configuration

- name: Delete MySQL user
  mysql_user:
    name: "{{ mysql_user }}"
    state: absent
    column_case_sensitive: true
  tags:
    - cleanup

- name: Create MySQL user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
    column_case_sensitive: true
  tags:
    - deployment

- name: Delete Database
  mysql_db:
    name: "{{ mysql_db }}"
    state: absent
  tags:
    - cleanup

- name: Create Database
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
  tags:
    - deployment

- name: Import sample data
  ansible.builtin.copy:
    src: "data/dump.sql"
    dest: "/tmp/dump.sql"
  tags:
    - deployment

- name: Insert sample data
  mysql_db:
    name: "{{ mysql_db }}"
    target: "/tmp/dump.sql"
    state: import
  tags:
    - deployment
