all:
  hosts:
    vm-web-prod-01:
      ansible_host: '{{ lookup("ansible.builtin.env", "VM_PROD") }}'
      ansible_user: debian
    vm-web-staging-01:
      ansible_host: '{{ lookup("ansible.builtin.env", "VM_DEV") }}'
      ansible_user: debian
  children:
    webservers:
      hosts:
        vm-web-prod-01:
        vm-web-staging-01:
    dbservers:
      hosts:
        vm-web-prod-01:
        vm-web-staging-01:
